# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bB9D3Agedj9Hxc0BEki7MQ01eCkLJDpS
"""

print("Hello! I am cleaning robo.")
print("Today we will build a cleaning robot together:")
print(2 + 3, "is the answer to 2 + 3")

room = ["D", "C", "D", "D", "C"]

def show_room(room):
    picture = ""
    for spot in room:
        if spot == "D":
            picture += "💩 "
        else:
            picture += "✨ "
    print(picture)

print("Our room right now:")
show_room(room)

def clean_spot(spot):
    if spot == "D":
        return "C"
    else:
        return "C"

result = clean_spot("D")
print("The robot looked at a dirty spot 💩 and made it:", result,
      "(C means clean ✨)")

print("BEFORE - the dirty room:")
show_room(room)

for i in range(len(room)):
    room[i] = clean_spot(room[i])
    print("After cleaning spot number", i + 1, ":")
    show_room(room)

print()
print("AFTER - all done! ⭐⭐⭐⭐⭐⭐")

print("create a 🤖chatbot:")

while True:
  user = input("you:\n").lower()
  if user =="hi" or user =="hello":
    print("🤖chatbot:hello ! how are you?")
  elif "how are you"in user:
    print("🤖chatbot:i'm fine,thank you")
  elif "what is your name" in user:
    print("🤖chatbot:my name is PRANEETH")
  elif "bye" in user:
    print("🤖chatbot:bye bye")
    break
  else:
    print("🤖chatbot:i don't understand")

spam_words = [
    "lottery",
    "claim",
    "click",
    "winner"
    "prize",
    "free",
    "lobbery",
    "money",
]
email = input("Enter your email message:\n")
email = email.lower()
for word in spam_words:
    if word in email:
        print("This is a spam email")
        break
else:
    print("This is not a spam email")